version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: netops-backend
    restart: always
    ports:
      - "2500:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./.env:/app/.env
    environment:
      - PORT=4000
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:2000
    networks:
      - netops-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    container_name: netops-frontend
    restart: always
    ports:
      - "2000:2000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env
    networks:
      - netops-network
    depends_on:
      - backend

networks:
  netops-network:
    driver: bridge
