server {
    listen 80;
    server_name _;

    # 1. จัดการ Backend API 
    location /network-management/8100/api/ {
        # Backend run at port 4000
        proxy_pass http://backend:4000/api/;
    }

    # จัดการกรณีไม่มี trailing slash
    location = /network-management/8100 {
        return 301 /network-management/8100/;
    }

    # 2. จัดการ Frontend Page
    # ใช้ trailing slash เพื่อตัด /network-management/8100 ออกก่อนส่งให้ Frontend
    location /network-management/8100/ {
        proxy_pass http://frontend:80/;
    }

    # 3. อำนวยความสะดวก (Redirect)
    location = / {
        return 302 /network-management/8100/;
    }
}
